services:
  contacts-api:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    restart: on-failure
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
  